export const metadata = {
  title: "Detalles del Pokémon",
  description: "Generated by create next app",
  icons: {
    icon: "/icono1.png",
    shortcut: "/icono1.png",
    apple: "/icono1.png",
  },
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
