import "./globals.css";
import { Suspense } from "react";
import Spinner from "../components/Spinner";

export const metadata = {
  title: "Pokémon App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.png",
    shortcut: "/logo1.png",
    apple: "/logo1.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense
          fallback={
            <div className="loading">
              <Spinner />
              <p className="p-loading">Cargando Aplicación...</p>
            </div>
          }
        >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
